### ISSUE TITLE
TD et TP complet

### ISSUE THREAD

**Issue by mkcisse** [dreimert/bitcoin-TD1#6]
Salut,
est-ce possible d'obtenir les autres TDs et TPs ?
J'ai également vu que l'insa lyon avait mis en place une crypto basée sur litecoin.
Peut-on obtenir la doc ? Il est difficile de trouver de la documentation francophoene technique ?

Cordialement

**Comment by dreimert** [comment]
Bonjour,

C'est un vieux TD, vous pouvez retrouver l'ensemble de mes cours sur https://cours.reimert.fr/ et celui-ci et les TD/TPs associés dans Blockchain -> archives. Vous pouvez y trouver un ensemble de TD / TP pour comprendre les bases en codant. C'est toujours en amélioration perpétuelle.

Pour la crypto INSAcoin, c'était juste une démonstration pour une soirée / quelques jours. À ma connaissance, elle ne fonctionne plus.

Pour une bonne documentation complète en français, je n'en connais pas. Il y a plein d'articles un peu partout.

Vous pouvez trouver mon mail dans mes commits si vous avez des questions.
